services:
  backend:
    container_name: auth_backend
    build: ./
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - HTTP_HOST=0.0.0.0
    expose:
      - "3000"
  gateway:
    container_name: auth_gateway
    build:
      context: ./
      dockerfile: Dockerfile.gateway
    depends_on:
      - backend
    ports:
      - "80:80"
