version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  mycharts-parser:
    build:
      context: ../microservice-parser
      dockerfile: ../microservice-parser/Dockerfile
    volumes:
      - ../microservice-parser:/app
    ports:
      - "3001:3001"

  mycharts-frontend:
    build:
      context: ../microservice-frontend
      dockerfile: ../microservice-frontend/Dockerfile
    ports:
      - "3000:3000"