services:
  backend:
    container_name: auth_backend
    build: ./
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=3000
    expose:
      - "3000"
  gateway:
    container_name: auth_gateway
    build:
      context: ./
      dockerfile: ./gateway.Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
