services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    expose:
      - "2181"

  kafka:
    container_name: kafka_broker
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka_broker
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=

  database:
    container_name: user_management_database
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./user_management_database_volume/:/data/db/

  backend:
    container_name: user_management_backend
    build: ./
    depends_on:
      - kafka
      - database
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - HTTP_HOST=0.0.0.0
      - MONGO_HOST=user_management_database
    expose:
      - "3000"
    ports:
      - "3000:3000"
